### ISSUE TITLE
Copy Edit

### ISSUE THREAD

**Issue by MarcScott** [raspberrypilearning/sense-hat-marble-maze#1]
Hi @LornaLynch, could I get another copy edit on this please.

Thanks

**Comment by LornaLynch** [comment]
Sure. I'm working on MagPi stuff as well for the next few days too, but I'll be sure to get this covered too.

**Comment by LornaLynch** [comment]
Under the "drawing the maze" section (and possibly elsewhere) the LED at (4,6) in the matrix is marked as 'g': is this a typo? I was thinking it should be 'b'.

**Comment by LornaLynch** [comment]
Ignore that: I've just noticed that a few of the matrices have this error, but others don't. Updating now.

**Comment by MarcScott** [comment]
Yep. My copy and paste error. It needs to be green in the last section. That's some pretty awesome skills to spot that in an 8x8 grid. Cheers

**Comment by LornaLynch** [comment]
Not a problem :)
